.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. statusquo_qt test_statusquo_qt
clean: FORCE
	$(MAKE) -C .. statusquo_qt_clean test_statusquo_qt_clean
check: FORCE
	$(MAKE) -C .. test_statusquo_qt_check
statusquo-qt statusquo-qt.exe: FORCE
	 $(MAKE) -C .. statusquo_qt
